/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * ClassIsland.ManagementServer.Server - version 1.0
 *
 *
 *
 * OpenAPI version: 3.0.1
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'AppSettings.get_api_v1_default_settings': ['GET', '/api/v1/default-settings'],
  'AppSettings.post_api_v1_default_settings': ['POST', '/api/v1/default-settings'],
  'AppSettings.get_api_v1_default_settings_id': ['GET', '/api/v1/default-settings/{id}'],
  'AppSettings.post_api_v1_default_settings_id': ['POST', '/api/v1/default-settings/{id}'],
  'AppSettings.delete_api_v1_default_settings_id': ['DELETE', '/api/v1/default-settings/{id}'],
  'Assignees.get_api_v1_assignees_id': ['GET', '/api/v1/assignees/{id}'],
  'Assignees.post_api_v1_assignees_id': ['POST', '/api/v1/assignees/{id}'],
  'Assignees.delete_api_v1_assignees_id': ['DELETE', '/api/v1/assignees/{id}'],
  'Assignees.post_api_v1_assignees': ['POST', '/api/v1/assignees'],
  'classislandManagementserverServer.post_api_v1_identity_register': ['POST', '/api/v1/identity/register'],
  'classislandManagementserverServer.post_api_v1_identity_login': ['POST', '/api/v1/identity/login'],
  'classislandManagementserverServer.post_api_v1_identity_refresh': ['POST', '/api/v1/identity/refresh'],
  'classislandManagementserverServer.mapidentityapiApiV1IdentityConfirmemail': ['GET', '/api/v1/identity/confirmEmail'],
  'classislandManagementserverServer.post_api_v1_identity_resendconfirmationemail': [
    'POST',
    '/api/v1/identity/resendConfirmationEmail'
  ],
  'classislandManagementserverServer.post_api_v1_identity_forgotpassword': ['POST', '/api/v1/identity/forgotPassword'],
  'classislandManagementserverServer.post_api_v1_identity_resetpassword': ['POST', '/api/v1/identity/resetPassword'],
  'classislandManagementserverServer.post_api_v1_identity_manage_2fa': ['POST', '/api/v1/identity/manage/2fa'],
  'classislandManagementserverServer.get_api_v1_identity_manage_info': ['GET', '/api/v1/identity/manage/info'],
  'classislandManagementserverServer.post_api_v1_identity_manage_info': ['POST', '/api/v1/identity/manage/info'],
  'ClientCommandDeliver.post_api_v1_client_commands_show_notification': [
    'POST',
    '/api/v1/client-commands/show-notification'
  ],
  'ClientCommandDeliver.post_api_v1_client_commands_restart_app': ['POST', '/api/v1/client-commands/restart-app'],
  'ClientRegistry.get_api_v1_clients_registry_list': ['GET', '/api/v1/clients_registry/list'],
  'ClientRegistry.post_api_v1_clients_registry_register': ['POST', '/api/v1/clients_registry/register'],
  'ClientRegistry.delete_api_v1_clients_registry_unregister': ['DELETE', '/api/v1/clients_registry/unregister'],
  'ClientRegistry.get_api_v1_clients_registry_query_cuid': ['GET', '/api/v1/clients_registry/query/{cuid}'],
  'Manifest.get_api_v1_client_cuid_manifest': ['GET', '/api/v1/client/{cuid}/manifest'],
  'ObjectsDelivery.get_api_v1_client_cuid_subjects': ['GET', '/api/v1/client/{cuid}/subjects'],
  'ObjectsDelivery.get_api_v1_client_cuid_timelayouts': ['GET', '/api/v1/client/{cuid}/timelayouts'],
  'ObjectsDelivery.get_api_v1_client_cuid_classplans': ['GET', '/api/v1/client/{cuid}/classplans'],
  'ObjectsDelivery.get_api_v1_client_cuid_policy': ['GET', '/api/v1/client/{cuid}/policy'],
  'ObjectsDelivery.get_api_v1_client_cuid_default_settings': ['GET', '/api/v1/client/{cuid}/default-settings'],
  'Policies.get_api_v1_policies': ['GET', '/api/v1/policies'],
  'Policies.post_api_v1_policies': ['POST', '/api/v1/policies'],
  'Policies.get_api_v1_policies_id': ['GET', '/api/v1/policies/{id}'],
  'Policies.post_api_v1_policies_id': ['POST', '/api/v1/policies/{id}'],
  'Policies.delete_api_v1_policies_id': ['DELETE', '/api/v1/policies/{id}'],
  'Profiles.post_api_v1_profiles_upload': ['POST', '/api/v1/profiles/upload']
};
