/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * ClassIsland.ManagementServer.Server - version 1.0
 *
 *
 *
 * OpenAPI version: 3.0.1
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'appsettings.get_api_v1_default_settings': ['GET', '/api/v1/default-settings'],
  'appsettings.post_api_v1_default_settings': ['POST', '/api/v1/default-settings'],
  'appsettings.get_api_v1_default_settings_id': ['GET', '/api/v1/default-settings/{id}'],
  'appsettings.post_api_v1_default_settings_id': ['POST', '/api/v1/default-settings/{id}'],
  'appsettings.delete_api_v1_default_settings_id': ['DELETE', '/api/v1/default-settings/{id}'],
  'assignees.get_api_v1_assignees_all_id': ['GET', '/api/v1/assignees/all/{id}'],
  'assignees.post_api_v1_assignees_all_id': ['POST', '/api/v1/assignees/all/{id}'],
  'assignees.delete_api_v1_assignees_all_id': ['DELETE', '/api/v1/assignees/all/{id}'],
  'assignees.post_api_v1_assignees_all': ['POST', '/api/v1/assignees/all'],
  'assignees.get_api_v1_assignees_by_object_objecttype_id': ['GET', '/api/v1/assignees/by-object/{objectType}/{id}'],
  'identity.post_api_v1_identity_register': ['POST', '/api/v1/identity/register'],
  'identity.post_api_v1_identity_login': ['POST', '/api/v1/identity/login'],
  'identity.post_api_v1_identity_refresh': ['POST', '/api/v1/identity/refresh'],
  'identity.mapidentityapiApiV1IdentityConfirmemail': ['GET', '/api/v1/identity/confirmEmail'],
  'identity.post_api_v1_identity_resendconfirmationemail': ['POST', '/api/v1/identity/resendConfirmationEmail'],
  'identity.post_api_v1_identity_forgotpassword': ['POST', '/api/v1/identity/forgotPassword'],
  'identity.post_api_v1_identity_resetpassword': ['POST', '/api/v1/identity/resetPassword'],
  'identity.post_api_v1_identity_manage_2fa': ['POST', '/api/v1/identity/manage/2fa'],
  'identity.get_api_v1_identity_manage_info': ['GET', '/api/v1/identity/manage/info'],
  'identity.post_api_v1_identity_manage_info': ['POST', '/api/v1/identity/manage/info'],
  'classplans.get_api_v1_profiles_classplans': ['GET', '/api/v1/profiles/classPlans'],
  'classplans.put_api_v1_profiles_classplans': ['PUT', '/api/v1/profiles/classPlans'],
  'classplans.get_api_v1_profiles_classplans_id': ['GET', '/api/v1/profiles/classPlans/{id}'],
  'classplans.put_api_v1_profiles_classplans_id': ['PUT', '/api/v1/profiles/classPlans/{id}'],
  'classplans.delete_api_v1_profiles_classplans_id': ['DELETE', '/api/v1/profiles/classPlans/{id}'],
  'clientcommanddeliver.post_api_v1_client_commands_show_notification': [
    'POST',
    '/api/v1/client-commands/show-notification'
  ],
  'clientcommanddeliver.post_api_v1_client_commands_restart_app': ['POST', '/api/v1/client-commands/restart-app'],
  'clientregistry.get_api_v1_clients_registry_list': ['GET', '/api/v1/clients_registry/list'],
  'clientregistry.post_api_v1_clients_registry_register': ['POST', '/api/v1/clients_registry/register'],
  'clientregistry.delete_api_v1_clients_registry_unregister': ['DELETE', '/api/v1/clients_registry/unregister'],
  'clientregistry.get_api_v1_clients_registry_query_cuid': ['GET', '/api/v1/clients_registry/query/{cuid}'],
  'clientregistry.get_api_v1_clients_registry_client_configure': ['GET', '/api/v1/clients_registry/client_configure'],
  'manifest.get_api_v1_client_cuid_manifest': ['GET', '/api/v1/client/{cuid}/manifest'],
  'objectsdelivery.get_api_v1_client_cuid_subjects': ['GET', '/api/v1/client/{cuid}/subjects'],
  'objectsdelivery.get_api_v1_client_cuid_timelayouts': ['GET', '/api/v1/client/{cuid}/timelayouts'],
  'objectsdelivery.get_api_v1_client_cuid_classplans': ['GET', '/api/v1/client/{cuid}/classplans'],
  'objectsdelivery.get_api_v1_client_cuid_policy': ['GET', '/api/v1/client/{cuid}/policy'],
  'objectsdelivery.get_api_v1_client_cuid_default_settings': ['GET', '/api/v1/client/{cuid}/default-settings'],
  'policies.get_api_v1_policies': ['GET', '/api/v1/policies'],
  'policies.post_api_v1_policies': ['POST', '/api/v1/policies'],
  'policies.get_api_v1_policies_id': ['GET', '/api/v1/policies/{id}'],
  'policies.post_api_v1_policies_id': ['POST', '/api/v1/policies/{id}'],
  'policies.delete_api_v1_policies_id': ['DELETE', '/api/v1/policies/{id}'],
  'profiles.post_api_v1_profiles_upload': ['POST', '/api/v1/profiles/upload'],
  'subjects.get_api_v1_profiles_subjects': ['GET', '/api/v1/profiles/subjects'],
  'subjects.put_api_v1_profiles_subjects': ['PUT', '/api/v1/profiles/subjects'],
  'subjects.put_api_v1_profiles_subjects_id': ['PUT', '/api/v1/profiles/subjects/{id}'],
  'subjects.delete_api_v1_profiles_subjects_id': ['DELETE', '/api/v1/profiles/subjects/{id}'],
  'timelayouts.get_api_v1_profiles_timelayouts': ['GET', '/api/v1/profiles/timeLayouts'],
  'timelayouts.put_api_v1_profiles_timelayouts': ['PUT', '/api/v1/profiles/timeLayouts'],
  'timelayouts.get_api_v1_profiles_timelayouts_id': ['GET', '/api/v1/profiles/timeLayouts/{id}'],
  'timelayouts.put_api_v1_profiles_timelayouts_id': ['PUT', '/api/v1/profiles/timeLayouts/{id}'],
  'timelayouts.delete_api_v1_profiles_timelayouts_id': ['DELETE', '/api/v1/profiles/timeLayouts/{id}'],
  'usersinfo.get_api_v1_users_info_id': ['GET', '/api/v1/users/info/{id}']
};
