/* tslint:disable */
/* eslint-disable */
/**
 * ClassIsland.ManagementServer.Server - version 1.0
 *
 *
 *
 * OpenAPI version: 3.0.1
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
import type { Alova, AlovaMethodCreateConfig, AlovaGenerics, Method } from 'alova';
import type { $$userConfigMap, alovaInstance } from '.';
import type apiDefinitions from './apiDefinitions';

type CollapsedAlova = typeof alovaInstance;
type UserMethodConfigMap = typeof $$userConfigMap;

type Alova2MethodConfig<Responded> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Omit<
        AlovaMethodCreateConfig<
          AlovaGenerics<Responded, any, RequestConfig, Response, ResponseHeader, L1Cache, L2Cache, SE>,
          any,
          Responded
        >,
        'params'
      >
    : never;

// Extract the return type of transform function that define in $$userConfigMap, if it not exists, use the default type.
type ExtractUserDefinedTransformed<
  DefinitionKey extends keyof typeof apiDefinitions,
  Default
> = DefinitionKey extends keyof UserMethodConfigMap
  ? UserMethodConfigMap[DefinitionKey]['transform'] extends (...args: any[]) => any
    ? Awaited<ReturnType<UserMethodConfigMap[DefinitionKey]['transform']>>
    : Default
  : Default;
type Alova2Method<
  Responded,
  DefinitionKey extends keyof typeof apiDefinitions,
  CurrentConfig extends Alova2MethodConfig<any>
> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Method<
        AlovaGenerics<
          CurrentConfig extends undefined
            ? ExtractUserDefinedTransformed<DefinitionKey, Responded>
            : CurrentConfig['transform'] extends (...args: any[]) => any
              ? Awaited<ReturnType<CurrentConfig['transform']>>
              : ExtractUserDefinedTransformed<DefinitionKey, Responded>,
          any,
          RequestConfig,
          Response,
          ResponseHeader,
          L1Cache,
          L2Cache,
          SE
        >
      >
    : never;

export type Setting = {
  id?: string;
  name?: string;
  description?: string;
  settings?: string;
};
export type ObjectTypes = 0 | 1 | 2 | 3 | 4 | 5;
export type AssigneeTypes = 0 | 1 | 2 | 3;
export type ObjectUpdate = {
  id?: number;
  objectId?: string;
  objectType?: ObjectTypes;
  targetCuid?: string;
  updateTime?: string;
  targetClient?: Client;
};
export type ClientGroup = {
  id?: number;
  name?: string;
  clients?: Client[];
  objectsAssignees?: ObjectsAssignee[];
};
export type Client = {
  cuid?: string;
  id?: string;
  registerTime?: string;
  groupId?: number;
  policyVersion?: number;
  timeLayoutVersion?: number;
  subjectsVersion?: number;
  defaultSettingsVersion?: number;
  classPlanVersion?: number;
  group?: ClientGroup;
  objectUpdates?: ObjectUpdate[];
  objectsAssignees?: ObjectsAssignee[];
};
export type ObjectsAssignee = {
  id?: number;
  objectId?: string;
  objectType?: ObjectTypes;
  targetClientId?: string;
  targetClientCuid?: string;
  targetGroupId?: number;
  assigneeType?: AssigneeTypes;
  targetClientCu?: Client;
  targetGroup?: ClientGroup;
};
export type RegisterRequest = {
  email?: string;
  password?: string;
};
export type AccessTokenResponse = {
  tokenType?: string;
  accessToken?: string;
  expiresIn?: number;
  refreshToken?: string;
};
export type LoginRequest = {
  email?: string;
  password?: string;
  twoFactorCode?: string;
  twoFactorRecoveryCode?: string;
};
export type RefreshRequest = {
  refreshToken?: string;
};
export type ResendConfirmationEmailRequest = {
  email?: string;
};
export type ForgotPasswordRequest = {
  email?: string;
};
export type ResetPasswordRequest = {
  email?: string;
  resetCode?: string;
  newPassword?: string;
};
export type TwoFactorResponse = {
  sharedKey?: string;
  recoveryCodesLeft?: number;
  recoveryCodes?: string[];
  isTwoFactorEnabled?: boolean;
  isMachineRemembered?: boolean;
};
export type TwoFactorRequest = {
  enable?: boolean;
  twoFactorCode?: string;
  resetSharedKey?: boolean;
  resetRecoveryCodes?: boolean;
  forgetMachine?: boolean;
};
export type InfoResponse = {
  email?: string;
  isEmailConfirmed?: boolean;
};
export type InfoRequest = {
  newEmail?: string;
  newPassword?: string;
  oldPassword?: string;
};
export type TimeRule = {
  isActive?: boolean;
  weekDay?: number;
  weekCountDiv?: number;
};
export type ClassInfo = {
  isActive?: boolean;
  subjectId?: string;
};
export type ClassPlan = {
  isActive?: boolean;
  attachedObjects?: Record<string, unknown>;
  timeLayoutId?: string;
  timeRule?: TimeRule;
  classes?: ClassInfo[];
  name?: string;
  isOverlay?: boolean;
  overlaySourceId?: string;
  overlaySetupTime?: string;
  isEnabled?: boolean;
  associatedGroup?: string;
};
export type CommandTypes = 0 | 1 | 2 | 3 | 4 | 5 | 6;
export type SendNotification = {
  messageMask?: string;
  messageContent?: string;
  overlayIconLeft?: number;
  overlayIconRight?: number;
  isEmergency?: boolean;
  isSpeechEnabled?: boolean;
  isEffectEnabled?: boolean;
  isSoundEnabled?: boolean;
  isTopmost?: boolean;
  durationSeconds?: number;
  repeatCounts?: number;
};
export type SendNotificationRequest = {
  targets?: ObjectsAssignee[];
  type?: CommandTypes;
  payload?: SendNotification;
};
export type RestartAppRequest = {
  targets?: ObjectsAssignee[];
  type?: CommandTypes;
};
export type ManagementPolicy = {
  isActive?: boolean;
  disableProfileClassPlanEditing?: boolean;
  disableProfileTimeLayoutEditing?: boolean;
  disableProfileSubjectsEditing?: boolean;
  disableProfileEditing?: boolean;
  disableSettingsEditing?: boolean;
  disableSplashCustomize?: boolean;
  disableDebugMenu?: boolean;
  allowExitManagement?: boolean;
};
export type Policy = {
  id?: string;
  name?: string;
  isEnabled?: boolean;
  content?: ManagementPolicy;
};
export type TimeLayoutItem = {
  isActive?: boolean;
  attachedObjects?: Record<string, unknown>;
  startSecond?: string;
  endSecond?: string;
  timeType?: number;
  isHideDefault?: boolean;
  defaultClassId?: string;
};
export type TimeLayout = {
  isActive?: boolean;
  attachedObjects?: Record<string, unknown>;
  name?: string;
  layouts?: TimeLayoutItem[];
};
export type Subject = {
  isActive?: boolean;
  attachedObjects?: Record<string, unknown>;
  name?: string;
  initial?: string;
  teacherName?: string;
  isOutDoor?: boolean;
};
export type ClassPlanGroup = {
  isActive?: boolean;
  name?: string;
  isGlobal?: boolean;
};
export type TempClassPlanGroupType = 0 | 1;
export type Profile = {
  isActive?: boolean;
  name?: string;
  timeLayouts?: Record<string, TimeLayout>;
  classPlans?: Record<string, ClassPlan>;
  subjects?: Record<string, Subject>;
  isOverlayClassPlanEnabled?: boolean;
  overlayClassPlanId?: string;
  tempClassPlanId?: string;
  tempClassPlanSetupTime?: string;
  classPlanGroups?: Record<string, ClassPlanGroup>;
  selectedClassPlanGroupId?: string;
  tempClassPlanGroupId?: string;
  tempClassPlanGroupExpireTime?: string;
  isTempClassPlanGroupEnabled?: boolean;
  tempClassPlanGroupType?: TempClassPlanGroupType;
};
export type TimeOnly = {
  hour?: number;
  minute?: number;
  second?: number;
  millisecond?: number;
  microsecond?: number;
  nanosecond?: number;
  ticks?: number;
};
export type ProfileTimeLayoutTimePoint = {
  internalId?: number;
  parentId?: string;
  index?: number;
  start?: TimeOnly;
  end?: TimeOnly;
  timeType?: number;
  defaultSubjectId?: string;
  isHideDefault?: boolean;
  parent?: ProfileTimeLayout;
  attachedObjects?: Record<string, unknown>;
};
export type ProfileTimeLayout = {
  id?: string;
  name?: string;
  groupId?: string;
  group?: ProfileGroup;
  profileClassPlans?: ProfileClassplan[];
  profileTimelayoutTimepoints?: ProfileTimeLayoutTimePoint[];
  attachedObjects?: Record<string, unknown>;
};
export type ProfileClassPlanClass = {
  internalId?: number;
  index?: number;
  parentId?: string;
  subjectId?: string;
  parent?: ProfileClassplan;
  subject?: ProfileSubject;
  attachedObjects?: Record<string, unknown>;
};
export type ProfileClassplan = {
  id?: string;
  name?: string;
  groupId?: string;
  weekDay?: number;
  weekDiv?: number;
  timeLayoutId?: string;
  isEnabled?: boolean;
  group?: ProfileGroup;
  profileClassPlanClasses?: ProfileClassPlanClass[];
  timeLayout?: ProfileTimeLayout;
  attachedObjects?: Record<string, unknown>;
};
export type ProfileGroup = {
  id?: string;
  name?: string;
  description?: string;
  profileClassplans?: ProfileClassplan[];
  profileSubjects?: ProfileSubject[];
  profileTimelayouts?: ProfileTimeLayout[];
};
export type ProfileSubject = {
  id?: string;
  groupId?: string;
  name?: string;
  initials?: string;
  isOutDoor?: boolean;
  group?: ProfileGroup;
  profileClassplanClasses?: ProfileClassPlanClass[];
  attachedObjects?: Record<string, unknown>;
};
declare global {
  interface Apis {
    appsettings: {
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api/v1/default-settings
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      get_api_v1_default_settings<Config extends Alova2MethodConfig<unknown>>(
        config?: Config
      ): Alova2Method<unknown, 'appsettings.get_api_v1_default_settings', Config>;
      /**
       * ---
       *
       * [POST]
       *
       * **path:** /api/v1/default-settings
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   id?: string
       *   name?: string
       *   description?: string
       *   settings?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      post_api_v1_default_settings<
        Config extends Alova2MethodConfig<unknown> & {
          data: Setting;
        }
      >(
        config: Config
      ): Alova2Method<unknown, 'appsettings.post_api_v1_default_settings', Config>;
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api/v1/default-settings/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // [required]
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      get_api_v1_default_settings_id<
        Config extends Alova2MethodConfig<unknown> & {
          pathParams: {
            /**
             * [required]
             */
            id: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<unknown, 'appsettings.get_api_v1_default_settings_id', Config>;
      /**
       * ---
       *
       * [POST]
       *
       * **path:** /api/v1/default-settings/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // [required]
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   id?: string
       *   name?: string
       *   description?: string
       *   settings?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      post_api_v1_default_settings_id<
        Config extends Alova2MethodConfig<unknown> & {
          pathParams: {
            /**
             * [required]
             */
            id: string;
          };
          data: Setting;
        }
      >(
        config: Config
      ): Alova2Method<unknown, 'appsettings.post_api_v1_default_settings_id', Config>;
      /**
       * ---
       *
       * [DELETE]
       *
       * **path:** /api/v1/default-settings/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // [required]
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      delete_api_v1_default_settings_id<
        Config extends Alova2MethodConfig<unknown> & {
          pathParams: {
            /**
             * [required]
             */
            id: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<unknown, 'appsettings.delete_api_v1_default_settings_id', Config>;
    };
    assignees: {
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api/v1/assignees/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // [required]
       *   id: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      get_api_v1_assignees_id<
        Config extends Alova2MethodConfig<unknown> & {
          pathParams: {
            /**
             * [required]
             */
            id: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<unknown, 'assignees.get_api_v1_assignees_id', Config>;
      /**
       * ---
       *
       * [POST]
       *
       * **path:** /api/v1/assignees/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // [required]
       *   id: number
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   id?: number
       *   objectId?: string
       *   objectType?: 0 | 1 | 2 | 3 | 4 | 5
       *   targetClientId?: string
       *   targetClientCuid?: string
       *   targetGroupId?: number
       *   assigneeType?: 0 | 1 | 2 | 3
       *   targetClientCu?: {
       *     cuid?: string
       *     id?: string
       *     registerTime?: string
       *     groupId?: number
       *     policyVersion?: number
       *     timeLayoutVersion?: number
       *     subjectsVersion?: number
       *     defaultSettingsVersion?: number
       *     classPlanVersion?: number
       *     group?: {
       *       id?: number
       *       name?: string
       *       clients?: Array<Client>
       *       objectsAssignees?: Array<ObjectsAssignee>
       *     }
       *     objectUpdates?: Array<{
       *       id?: number
       *       objectId?: string
       *       objectType?: ObjectTypes
       *       targetCuid?: string
       *       updateTime?: string
       *       targetClient?: Client
       *     }>
       *     objectsAssignees?: Array<ObjectsAssignee>
       *   }
       *   targetGroup?: ClientGroup
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      post_api_v1_assignees_id<
        Config extends Alova2MethodConfig<unknown> & {
          pathParams: {
            /**
             * [required]
             */
            id: number;
          };
          data: ObjectsAssignee;
        }
      >(
        config: Config
      ): Alova2Method<unknown, 'assignees.post_api_v1_assignees_id', Config>;
      /**
       * ---
       *
       * [DELETE]
       *
       * **path:** /api/v1/assignees/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // [required]
       *   id: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      delete_api_v1_assignees_id<
        Config extends Alova2MethodConfig<unknown> & {
          pathParams: {
            /**
             * [required]
             */
            id: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<unknown, 'assignees.delete_api_v1_assignees_id', Config>;
      /**
       * ---
       *
       * [POST]
       *
       * **path:** /api/v1/assignees
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   id?: number
       *   objectId?: string
       *   objectType?: 0 | 1 | 2 | 3 | 4 | 5
       *   targetClientId?: string
       *   targetClientCuid?: string
       *   targetGroupId?: number
       *   assigneeType?: 0 | 1 | 2 | 3
       *   targetClientCu?: {
       *     cuid?: string
       *     id?: string
       *     registerTime?: string
       *     groupId?: number
       *     policyVersion?: number
       *     timeLayoutVersion?: number
       *     subjectsVersion?: number
       *     defaultSettingsVersion?: number
       *     classPlanVersion?: number
       *     group?: {
       *       id?: number
       *       name?: string
       *       clients?: Array<Client>
       *       objectsAssignees?: Array<ObjectsAssignee>
       *     }
       *     objectUpdates?: Array<{
       *       id?: number
       *       objectId?: string
       *       objectType?: ObjectTypes
       *       targetCuid?: string
       *       updateTime?: string
       *       targetClient?: Client
       *     }>
       *     objectsAssignees?: Array<ObjectsAssignee>
       *   }
       *   targetGroup?: ClientGroup
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      post_api_v1_assignees<
        Config extends Alova2MethodConfig<unknown> & {
          data: ObjectsAssignee;
        }
      >(
        config: Config
      ): Alova2Method<unknown, 'assignees.post_api_v1_assignees', Config>;
    };
    identity: {
      /**
       * ---
       *
       * [POST]
       *
       * **path:** /api/v1/identity/register
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   email?: string
       *   password?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      post_api_v1_identity_register<
        Config extends Alova2MethodConfig<unknown> & {
          data: RegisterRequest;
        }
      >(
        config: Config
      ): Alova2Method<unknown, 'identity.post_api_v1_identity_register', Config>;
      /**
       * ---
       *
       * [POST]
       *
       * **path:** /api/v1/identity/login
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   useCookies?: boolean
       *   useSessionCookies?: boolean
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   email?: string
       *   password?: string
       *   twoFactorCode?: string
       *   twoFactorRecoveryCode?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   tokenType?: string
       *   accessToken?: string
       *   expiresIn?: number
       *   refreshToken?: string
       * }
       * ```
       */
      post_api_v1_identity_login<
        Config extends Alova2MethodConfig<AccessTokenResponse> & {
          params: {
            useCookies?: boolean;
            useSessionCookies?: boolean;
          };
          data: LoginRequest;
        }
      >(
        config: Config
      ): Alova2Method<AccessTokenResponse, 'identity.post_api_v1_identity_login', Config>;
      /**
       * ---
       *
       * [POST]
       *
       * **path:** /api/v1/identity/refresh
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   refreshToken?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   tokenType?: string
       *   accessToken?: string
       *   expiresIn?: number
       *   refreshToken?: string
       * }
       * ```
       */
      post_api_v1_identity_refresh<
        Config extends Alova2MethodConfig<AccessTokenResponse> & {
          data: RefreshRequest;
        }
      >(
        config: Config
      ): Alova2Method<AccessTokenResponse, 'identity.post_api_v1_identity_refresh', Config>;
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api/v1/identity/confirmEmail
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   userId?: string
       *   code?: string
       *   changedEmail?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      mapidentityapiApiV1IdentityConfirmemail<
        Config extends Alova2MethodConfig<unknown> & {
          params: {
            userId?: string;
            code?: string;
            changedEmail?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<unknown, 'identity.mapidentityapiApiV1IdentityConfirmemail', Config>;
      /**
       * ---
       *
       * [POST]
       *
       * **path:** /api/v1/identity/resendConfirmationEmail
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   email?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      post_api_v1_identity_resendconfirmationemail<
        Config extends Alova2MethodConfig<unknown> & {
          data: ResendConfirmationEmailRequest;
        }
      >(
        config: Config
      ): Alova2Method<unknown, 'identity.post_api_v1_identity_resendconfirmationemail', Config>;
      /**
       * ---
       *
       * [POST]
       *
       * **path:** /api/v1/identity/forgotPassword
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   email?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      post_api_v1_identity_forgotpassword<
        Config extends Alova2MethodConfig<unknown> & {
          data: ForgotPasswordRequest;
        }
      >(
        config: Config
      ): Alova2Method<unknown, 'identity.post_api_v1_identity_forgotpassword', Config>;
      /**
       * ---
       *
       * [POST]
       *
       * **path:** /api/v1/identity/resetPassword
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   email?: string
       *   resetCode?: string
       *   newPassword?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      post_api_v1_identity_resetpassword<
        Config extends Alova2MethodConfig<unknown> & {
          data: ResetPasswordRequest;
        }
      >(
        config: Config
      ): Alova2Method<unknown, 'identity.post_api_v1_identity_resetpassword', Config>;
      /**
       * ---
       *
       * [POST]
       *
       * **path:** /api/v1/identity/manage/2fa
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   enable?: boolean
       *   twoFactorCode?: string
       *   resetSharedKey?: boolean
       *   resetRecoveryCodes?: boolean
       *   forgetMachine?: boolean
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   sharedKey?: string
       *   recoveryCodesLeft?: number
       *   recoveryCodes?: string[]
       *   isTwoFactorEnabled?: boolean
       *   isMachineRemembered?: boolean
       * }
       * ```
       */
      post_api_v1_identity_manage_2fa<
        Config extends Alova2MethodConfig<TwoFactorResponse> & {
          data: TwoFactorRequest;
        }
      >(
        config: Config
      ): Alova2Method<TwoFactorResponse, 'identity.post_api_v1_identity_manage_2fa', Config>;
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api/v1/identity/manage/info
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   email?: string
       *   isEmailConfirmed?: boolean
       * }
       * ```
       */
      get_api_v1_identity_manage_info<Config extends Alova2MethodConfig<InfoResponse>>(
        config?: Config
      ): Alova2Method<InfoResponse, 'identity.get_api_v1_identity_manage_info', Config>;
      /**
       * ---
       *
       * [POST]
       *
       * **path:** /api/v1/identity/manage/info
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   newEmail?: string
       *   newPassword?: string
       *   oldPassword?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   email?: string
       *   isEmailConfirmed?: boolean
       * }
       * ```
       */
      post_api_v1_identity_manage_info<
        Config extends Alova2MethodConfig<InfoResponse> & {
          data: InfoRequest;
        }
      >(
        config: Config
      ): Alova2Method<InfoResponse, 'identity.post_api_v1_identity_manage_info', Config>;
    };
    classplans: {
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api/v1/profiles/classPlans
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   pageIndex?: number
       *   pageSize?: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      get_api_v1_profiles_classplans<
        Config extends Alova2MethodConfig<unknown> & {
          params: {
            pageIndex?: number;
            pageSize?: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<unknown, 'classplans.get_api_v1_profiles_classplans', Config>;
      /**
       * ---
       *
       * [PUT]
       *
       * **path:** /api/v1/profiles/classPlans
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   isActive?: boolean
       *   attachedObjects?: Record<string, unknown>
       *   timeLayoutId?: string
       *   timeRule?: {
       *     isActive?: boolean
       *     weekDay?: number
       *     weekCountDiv?: number
       *   }
       *   classes?: Array<{
       *     isActive?: boolean
       *     subjectId?: string
       *   }>
       *   name?: string
       *   isOverlay?: boolean
       *   overlaySourceId?: string
       *   overlaySetupTime?: string
       *   isEnabled?: boolean
       *   associatedGroup?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      put_api_v1_profiles_classplans<
        Config extends Alova2MethodConfig<unknown> & {
          data: ClassPlan;
        }
      >(
        config: Config
      ): Alova2Method<unknown, 'classplans.put_api_v1_profiles_classplans', Config>;
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api/v1/profiles/classPlans/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // [required]
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      get_api_v1_profiles_classplans_id<
        Config extends Alova2MethodConfig<unknown> & {
          pathParams: {
            /**
             * [required]
             */
            id: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<unknown, 'classplans.get_api_v1_profiles_classplans_id', Config>;
      /**
       * ---
       *
       * [PUT]
       *
       * **path:** /api/v1/profiles/classPlans/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // [required]
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   isActive?: boolean
       *   attachedObjects?: Record<string, unknown>
       *   timeLayoutId?: string
       *   timeRule?: {
       *     isActive?: boolean
       *     weekDay?: number
       *     weekCountDiv?: number
       *   }
       *   classes?: Array<{
       *     isActive?: boolean
       *     subjectId?: string
       *   }>
       *   name?: string
       *   isOverlay?: boolean
       *   overlaySourceId?: string
       *   overlaySetupTime?: string
       *   isEnabled?: boolean
       *   associatedGroup?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      put_api_v1_profiles_classplans_id<
        Config extends Alova2MethodConfig<unknown> & {
          pathParams: {
            /**
             * [required]
             */
            id: string;
          };
          data: ClassPlan;
        }
      >(
        config: Config
      ): Alova2Method<unknown, 'classplans.put_api_v1_profiles_classplans_id', Config>;
      /**
       * ---
       *
       * [DELETE]
       *
       * **path:** /api/v1/profiles/classPlans/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // [required]
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      delete_api_v1_profiles_classplans_id<
        Config extends Alova2MethodConfig<unknown> & {
          pathParams: {
            /**
             * [required]
             */
            id: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<unknown, 'classplans.delete_api_v1_profiles_classplans_id', Config>;
    };
    clientcommanddeliver: {
      /**
       * ---
       *
       * [POST]
       *
       * **path:** /api/v1/client-commands/show-notification
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   targets?: Array<{
       *     id?: number
       *     objectId?: string
       *     objectType?: 0 | 1 | 2 | 3 | 4 | 5
       *     targetClientId?: string
       *     targetClientCuid?: string
       *     targetGroupId?: number
       *     assigneeType?: 0 | 1 | 2 | 3
       *     targetClientCu?: {
       *       cuid?: string
       *       id?: string
       *       registerTime?: string
       *       groupId?: number
       *       policyVersion?: number
       *       timeLayoutVersion?: number
       *       subjectsVersion?: number
       *       defaultSettingsVersion?: number
       *       classPlanVersion?: number
       *       group?: {
       *         id?: number
       *         name?: string
       *         clients?: Array<Client>
       *         objectsAssignees?: Array<ObjectsAssignee>
       *       }
       *       objectUpdates?: Array<{
       *         id?: number
       *         objectId?: string
       *         objectType?: ObjectTypes
       *         targetCuid?: string
       *         updateTime?: string
       *         targetClient?: Client
       *       }>
       *       objectsAssignees?: Array<ObjectsAssignee>
       *     }
       *     targetGroup?: ClientGroup
       *   }>
       *   type?: 0 | 1 | 2 | 3 | 4 | 5 | 6
       *   payload?: {
       *     messageMask?: string
       *     messageContent?: string
       *     overlayIconLeft?: number
       *     overlayIconRight?: number
       *     isEmergency?: boolean
       *     isSpeechEnabled?: boolean
       *     isEffectEnabled?: boolean
       *     isSoundEnabled?: boolean
       *     isTopmost?: boolean
       *     durationSeconds?: number
       *     repeatCounts?: number
       *   }
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      post_api_v1_client_commands_show_notification<
        Config extends Alova2MethodConfig<unknown> & {
          data: SendNotificationRequest;
        }
      >(
        config: Config
      ): Alova2Method<unknown, 'clientcommanddeliver.post_api_v1_client_commands_show_notification', Config>;
      /**
       * ---
       *
       * [POST]
       *
       * **path:** /api/v1/client-commands/restart-app
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   targets?: Array<{
       *     id?: number
       *     objectId?: string
       *     objectType?: 0 | 1 | 2 | 3 | 4 | 5
       *     targetClientId?: string
       *     targetClientCuid?: string
       *     targetGroupId?: number
       *     assigneeType?: 0 | 1 | 2 | 3
       *     targetClientCu?: {
       *       cuid?: string
       *       id?: string
       *       registerTime?: string
       *       groupId?: number
       *       policyVersion?: number
       *       timeLayoutVersion?: number
       *       subjectsVersion?: number
       *       defaultSettingsVersion?: number
       *       classPlanVersion?: number
       *       group?: {
       *         id?: number
       *         name?: string
       *         clients?: Array<Client>
       *         objectsAssignees?: Array<ObjectsAssignee>
       *       }
       *       objectUpdates?: Array<{
       *         id?: number
       *         objectId?: string
       *         objectType?: ObjectTypes
       *         targetCuid?: string
       *         updateTime?: string
       *         targetClient?: Client
       *       }>
       *       objectsAssignees?: Array<ObjectsAssignee>
       *     }
       *     targetGroup?: ClientGroup
       *   }>
       *   type?: 0 | 1 | 2 | 3 | 4 | 5 | 6
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      post_api_v1_client_commands_restart_app<
        Config extends Alova2MethodConfig<unknown> & {
          data: RestartAppRequest;
        }
      >(
        config: Config
      ): Alova2Method<unknown, 'clientcommanddeliver.post_api_v1_client_commands_restart_app', Config>;
    };
    clientregistry: {
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api/v1/clients_registry/list
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   pageIndex?: number
       *   pageSize?: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      get_api_v1_clients_registry_list<
        Config extends Alova2MethodConfig<unknown> & {
          params: {
            pageIndex?: number;
            pageSize?: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<unknown, 'clientregistry.get_api_v1_clients_registry_list', Config>;
      /**
       * ---
       *
       * [POST]
       *
       * **path:** /api/v1/clients_registry/register
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   cuid?: string
       *   id?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      post_api_v1_clients_registry_register<
        Config extends Alova2MethodConfig<unknown> & {
          params: {
            cuid?: string;
            id?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<unknown, 'clientregistry.post_api_v1_clients_registry_register', Config>;
      /**
       * ---
       *
       * [DELETE]
       *
       * **path:** /api/v1/clients_registry/unregister
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   Cuid?: string
       *   Id?: string
       *   RegisterTime?: string
       *   GroupId?: number
       *   PolicyVersion?: number
       *   TimeLayoutVersion?: number
       *   SubjectsVersion?: number
       *   DefaultSettingsVersion?: number
       *   ClassPlanVersion?: number
       *   'Group.Id'?: number
       *   'Group.Name'?: string
       *   'Group.Clients'?: Array<{
       *     cuid?: string
       *     id?: string
       *     registerTime?: string
       *     groupId?: number
       *     policyVersion?: number
       *     timeLayoutVersion?: number
       *     subjectsVersion?: number
       *     defaultSettingsVersion?: number
       *     classPlanVersion?: number
       *     group?: {
       *       id?: number
       *       name?: string
       *       clients?: Array<Client>
       *       objectsAssignees?: Array<ObjectsAssignee>
       *     }
       *     objectUpdates?: Array<{
       *       id?: number
       *       objectId?: string
       *       objectType?: ObjectTypes
       *       targetCuid?: string
       *       updateTime?: string
       *       targetClient?: Client
       *     }>
       *     objectsAssignees?: Array<ObjectsAssignee>
       *   }>
       *   'Group.ObjectsAssignees'?: Array<{
       *     id?: number
       *     objectId?: string
       *     objectType?: 0 | 1 | 2 | 3 | 4 | 5
       *     targetClientId?: string
       *     targetClientCuid?: string
       *     targetGroupId?: number
       *     assigneeType?: 0 | 1 | 2 | 3
       *     targetClientCu?: {
       *       cuid?: string
       *       id?: string
       *       registerTime?: string
       *       groupId?: number
       *       policyVersion?: number
       *       timeLayoutVersion?: number
       *       subjectsVersion?: number
       *       defaultSettingsVersion?: number
       *       classPlanVersion?: number
       *       group?: {
       *         id?: number
       *         name?: string
       *         clients?: Array<Client>
       *         objectsAssignees?: Array<ObjectsAssignee>
       *       }
       *       objectUpdates?: Array<{
       *         id?: number
       *         objectId?: string
       *         objectType?: ObjectTypes
       *         targetCuid?: string
       *         updateTime?: string
       *         targetClient?: Client
       *       }>
       *       objectsAssignees?: Array<ObjectsAssignee>
       *     }
       *     targetGroup?: ClientGroup
       *   }>
       *   ObjectUpdates?: Array<{
       *     id?: number
       *     objectId?: string
       *     objectType?: ObjectTypes
       *     targetCuid?: string
       *     updateTime?: string
       *     targetClient?: Client
       *   }>
       *   ObjectsAssignees?: Array<ObjectsAssignee>
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      delete_api_v1_clients_registry_unregister<
        Config extends Alova2MethodConfig<unknown> & {
          params: {
            Cuid?: string;
            Id?: string;
            RegisterTime?: string;
            GroupId?: number;
            PolicyVersion?: number;
            TimeLayoutVersion?: number;
            SubjectsVersion?: number;
            DefaultSettingsVersion?: number;
            ClassPlanVersion?: number;
            'Group.Id'?: number;
            'Group.Name'?: string;
            'Group.Clients'?: Client[];
            'Group.ObjectsAssignees'?: ObjectsAssignee[];
            ObjectUpdates?: ObjectUpdate[];
            ObjectsAssignees?: ObjectsAssignee[];
          };
        }
      >(
        config: Config
      ): Alova2Method<unknown, 'clientregistry.delete_api_v1_clients_registry_unregister', Config>;
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api/v1/clients_registry/query/{cuid}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // [required]
       *   cuid: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      get_api_v1_clients_registry_query_cuid<
        Config extends Alova2MethodConfig<unknown> & {
          pathParams: {
            /**
             * [required]
             */
            cuid: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<unknown, 'clientregistry.get_api_v1_clients_registry_query_cuid', Config>;
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api/v1/clients_registry/client_configure
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      get_api_v1_clients_registry_client_configure<Config extends Alova2MethodConfig<unknown>>(
        config?: Config
      ): Alova2Method<unknown, 'clientregistry.get_api_v1_clients_registry_client_configure', Config>;
    };
    manifest: {
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api/v1/client/{cuid}/manifest
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // [required]
       *   cuid: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      get_api_v1_client_cuid_manifest<
        Config extends Alova2MethodConfig<unknown> & {
          pathParams: {
            /**
             * [required]
             */
            cuid: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<unknown, 'manifest.get_api_v1_client_cuid_manifest', Config>;
    };
    objectsdelivery: {
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api/v1/client/{cuid}/subjects
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // [required]
       *   cuid: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      get_api_v1_client_cuid_subjects<
        Config extends Alova2MethodConfig<unknown> & {
          pathParams: {
            /**
             * [required]
             */
            cuid: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<unknown, 'objectsdelivery.get_api_v1_client_cuid_subjects', Config>;
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api/v1/client/{cuid}/timelayouts
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // [required]
       *   cuid: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      get_api_v1_client_cuid_timelayouts<
        Config extends Alova2MethodConfig<unknown> & {
          pathParams: {
            /**
             * [required]
             */
            cuid: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<unknown, 'objectsdelivery.get_api_v1_client_cuid_timelayouts', Config>;
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api/v1/client/{cuid}/classplans
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // [required]
       *   cuid: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      get_api_v1_client_cuid_classplans<
        Config extends Alova2MethodConfig<unknown> & {
          pathParams: {
            /**
             * [required]
             */
            cuid: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<unknown, 'objectsdelivery.get_api_v1_client_cuid_classplans', Config>;
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api/v1/client/{cuid}/policy
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // [required]
       *   cuid: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      get_api_v1_client_cuid_policy<
        Config extends Alova2MethodConfig<unknown> & {
          pathParams: {
            /**
             * [required]
             */
            cuid: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<unknown, 'objectsdelivery.get_api_v1_client_cuid_policy', Config>;
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api/v1/client/{cuid}/default-settings
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // [required]
       *   cuid: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      get_api_v1_client_cuid_default_settings<
        Config extends Alova2MethodConfig<unknown> & {
          pathParams: {
            /**
             * [required]
             */
            cuid: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<unknown, 'objectsdelivery.get_api_v1_client_cuid_default_settings', Config>;
    };
    policies: {
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api/v1/policies
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      get_api_v1_policies<Config extends Alova2MethodConfig<unknown>>(
        config?: Config
      ): Alova2Method<unknown, 'policies.get_api_v1_policies', Config>;
      /**
       * ---
       *
       * [POST]
       *
       * **path:** /api/v1/policies
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   id?: string
       *   name?: string
       *   isEnabled?: boolean
       *   content?: {
       *     isActive?: boolean
       *     disableProfileClassPlanEditing?: boolean
       *     disableProfileTimeLayoutEditing?: boolean
       *     disableProfileSubjectsEditing?: boolean
       *     disableProfileEditing?: boolean
       *     disableSettingsEditing?: boolean
       *     disableSplashCustomize?: boolean
       *     disableDebugMenu?: boolean
       *     allowExitManagement?: boolean
       *   }
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      post_api_v1_policies<
        Config extends Alova2MethodConfig<unknown> & {
          data: Policy;
        }
      >(
        config: Config
      ): Alova2Method<unknown, 'policies.post_api_v1_policies', Config>;
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api/v1/policies/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // [required]
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      get_api_v1_policies_id<
        Config extends Alova2MethodConfig<unknown> & {
          pathParams: {
            /**
             * [required]
             */
            id: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<unknown, 'policies.get_api_v1_policies_id', Config>;
      /**
       * ---
       *
       * [POST]
       *
       * **path:** /api/v1/policies/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // [required]
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   id?: string
       *   name?: string
       *   isEnabled?: boolean
       *   content?: {
       *     isActive?: boolean
       *     disableProfileClassPlanEditing?: boolean
       *     disableProfileTimeLayoutEditing?: boolean
       *     disableProfileSubjectsEditing?: boolean
       *     disableProfileEditing?: boolean
       *     disableSettingsEditing?: boolean
       *     disableSplashCustomize?: boolean
       *     disableDebugMenu?: boolean
       *     allowExitManagement?: boolean
       *   }
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      post_api_v1_policies_id<
        Config extends Alova2MethodConfig<unknown> & {
          pathParams: {
            /**
             * [required]
             */
            id: string;
          };
          data: Policy;
        }
      >(
        config: Config
      ): Alova2Method<unknown, 'policies.post_api_v1_policies_id', Config>;
      /**
       * ---
       *
       * [DELETE]
       *
       * **path:** /api/v1/policies/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // [required]
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      delete_api_v1_policies_id<
        Config extends Alova2MethodConfig<unknown> & {
          pathParams: {
            /**
             * [required]
             */
            id: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<unknown, 'policies.delete_api_v1_policies_id', Config>;
    };
    profiles: {
      /**
       * ---
       *
       * [POST]
       *
       * **path:** /api/v1/profiles/upload
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   replace?: boolean
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   isActive?: boolean
       *   name?: string
       *   timeLayouts?: Record<
       *     string,
       *     {
       *       isActive?: boolean
       *       attachedObjects?: Record<string, unknown>
       *       name?: string
       *       layouts?: Array<{
       *         isActive?: boolean
       *         attachedObjects?: Record<string, unknown>
       *         startSecond?: string
       *         endSecond?: string
       *         timeType?: number
       *         isHideDefault?: boolean
       *         defaultClassId?: string
       *       }>
       *     }
       *   >
       *   classPlans?: Record<
       *     string,
       *     {
       *       isActive?: boolean
       *       attachedObjects?: Record<string, unknown>
       *       timeLayoutId?: string
       *       timeRule?: {
       *         isActive?: boolean
       *         weekDay?: number
       *         weekCountDiv?: number
       *       }
       *       classes?: Array<{
       *         isActive?: boolean
       *         subjectId?: string
       *       }>
       *       name?: string
       *       isOverlay?: boolean
       *       overlaySourceId?: string
       *       overlaySetupTime?: string
       *       isEnabled?: boolean
       *       associatedGroup?: string
       *     }
       *   >
       *   subjects?: Record<
       *     string,
       *     {
       *       isActive?: boolean
       *       attachedObjects?: Record<string, unknown>
       *       name?: string
       *       initial?: string
       *       teacherName?: string
       *       isOutDoor?: boolean
       *     }
       *   >
       *   isOverlayClassPlanEnabled?: boolean
       *   overlayClassPlanId?: string
       *   tempClassPlanId?: string
       *   tempClassPlanSetupTime?: string
       *   classPlanGroups?: Record<
       *     string,
       *     {
       *       isActive?: boolean
       *       name?: string
       *       isGlobal?: boolean
       *     }
       *   >
       *   selectedClassPlanGroupId?: string
       *   tempClassPlanGroupId?: string
       *   tempClassPlanGroupExpireTime?: string
       *   isTempClassPlanGroupEnabled?: boolean
       *   tempClassPlanGroupType?: 0 | 1
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      post_api_v1_profiles_upload<
        Config extends Alova2MethodConfig<unknown> & {
          params: {
            replace?: boolean;
          };
          data: Profile;
        }
      >(
        config: Config
      ): Alova2Method<unknown, 'profiles.post_api_v1_profiles_upload', Config>;
    };
    subjects: {
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api/v1/profiles/subjects
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   pageIndex?: number
       *   pageSize?: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      get_api_v1_profiles_subjects<
        Config extends Alova2MethodConfig<unknown> & {
          params: {
            pageIndex?: number;
            pageSize?: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<unknown, 'subjects.get_api_v1_profiles_subjects', Config>;
      /**
       * ---
       *
       * [PUT]
       *
       * **path:** /api/v1/profiles/subjects
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   id?: string
       *   groupId?: string
       *   name?: string
       *   initials?: string
       *   isOutDoor?: boolean
       *   group?: {
       *     id?: string
       *     name?: string
       *     description?: string
       *     profileClassplans?: Array<{
       *       id?: string
       *       name?: string
       *       groupId?: string
       *       weekDay?: number
       *       weekDiv?: number
       *       timeLayoutId?: string
       *       isEnabled?: boolean
       *       group?: ProfileGroup
       *       profileClassPlanClasses?: Array<{
       *         internalId?: number
       *         index?: number
       *         parentId?: string
       *         subjectId?: string
       *         parent?: ProfileClassplan
       *         subject?: ProfileSubject
       *         attachedObjects?: Record<string, unknown>
       *       }>
       *       timeLayout?: {
       *         id?: string
       *         name?: string
       *         groupId?: string
       *         group?: ProfileGroup
       *         profileClassPlans?: Array<ProfileClassplan>
       *         profileTimelayoutTimepoints?: Array<{
       *           internalId?: number
       *           parentId?: string
       *           index?: number
       *           start?: {
       *             hour?: number
       *             minute?: number
       *             second?: number
       *             millisecond?: number
       *             microsecond?: number
       *             nanosecond?: number
       *             ticks?: number
       *           }
       *           end?: TimeOnly
       *           timeType?: number
       *           defaultSubjectId?: string
       *           isHideDefault?: boolean
       *           parent?: ProfileTimeLayout
       *           attachedObjects?: Record<string, unknown>
       *         }>
       *         attachedObjects?: Record<string, unknown>
       *       }
       *       attachedObjects?: Record<string, unknown>
       *     }>
       *     profileSubjects?: Array<ProfileSubject>
       *     profileTimelayouts?: Array<ProfileTimeLayout>
       *   }
       *   profileClassplanClasses?: Array<ProfileClassPlanClass>
       *   attachedObjects?: Record<string, unknown>
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      put_api_v1_profiles_subjects<
        Config extends Alova2MethodConfig<unknown> & {
          data: ProfileSubject;
        }
      >(
        config: Config
      ): Alova2Method<unknown, 'subjects.put_api_v1_profiles_subjects', Config>;
      /**
       * ---
       *
       * [PUT]
       *
       * **path:** /api/v1/profiles/subjects/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // [required]
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   id?: string
       *   groupId?: string
       *   name?: string
       *   initials?: string
       *   isOutDoor?: boolean
       *   group?: {
       *     id?: string
       *     name?: string
       *     description?: string
       *     profileClassplans?: Array<{
       *       id?: string
       *       name?: string
       *       groupId?: string
       *       weekDay?: number
       *       weekDiv?: number
       *       timeLayoutId?: string
       *       isEnabled?: boolean
       *       group?: ProfileGroup
       *       profileClassPlanClasses?: Array<{
       *         internalId?: number
       *         index?: number
       *         parentId?: string
       *         subjectId?: string
       *         parent?: ProfileClassplan
       *         subject?: ProfileSubject
       *         attachedObjects?: Record<string, unknown>
       *       }>
       *       timeLayout?: {
       *         id?: string
       *         name?: string
       *         groupId?: string
       *         group?: ProfileGroup
       *         profileClassPlans?: Array<ProfileClassplan>
       *         profileTimelayoutTimepoints?: Array<{
       *           internalId?: number
       *           parentId?: string
       *           index?: number
       *           start?: {
       *             hour?: number
       *             minute?: number
       *             second?: number
       *             millisecond?: number
       *             microsecond?: number
       *             nanosecond?: number
       *             ticks?: number
       *           }
       *           end?: TimeOnly
       *           timeType?: number
       *           defaultSubjectId?: string
       *           isHideDefault?: boolean
       *           parent?: ProfileTimeLayout
       *           attachedObjects?: Record<string, unknown>
       *         }>
       *         attachedObjects?: Record<string, unknown>
       *       }
       *       attachedObjects?: Record<string, unknown>
       *     }>
       *     profileSubjects?: Array<ProfileSubject>
       *     profileTimelayouts?: Array<ProfileTimeLayout>
       *   }
       *   profileClassplanClasses?: Array<ProfileClassPlanClass>
       *   attachedObjects?: Record<string, unknown>
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      put_api_v1_profiles_subjects_id<
        Config extends Alova2MethodConfig<unknown> & {
          pathParams: {
            /**
             * [required]
             */
            id: string;
          };
          data: ProfileSubject;
        }
      >(
        config: Config
      ): Alova2Method<unknown, 'subjects.put_api_v1_profiles_subjects_id', Config>;
      /**
       * ---
       *
       * [DELETE]
       *
       * **path:** /api/v1/profiles/subjects/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // [required]
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      delete_api_v1_profiles_subjects_id<
        Config extends Alova2MethodConfig<unknown> & {
          pathParams: {
            /**
             * [required]
             */
            id: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<unknown, 'subjects.delete_api_v1_profiles_subjects_id', Config>;
    };
    timelayouts: {
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api/v1/profiles/timeLayouts
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   pageIndex?: number
       *   pageSize?: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      get_api_v1_profiles_timelayouts<
        Config extends Alova2MethodConfig<unknown> & {
          params: {
            pageIndex?: number;
            pageSize?: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<unknown, 'timelayouts.get_api_v1_profiles_timelayouts', Config>;
      /**
       * ---
       *
       * [PUT]
       *
       * **path:** /api/v1/profiles/timeLayouts
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   isActive?: boolean
       *   attachedObjects?: Record<string, unknown>
       *   name?: string
       *   layouts?: Array<{
       *     isActive?: boolean
       *     attachedObjects?: Record<string, unknown>
       *     startSecond?: string
       *     endSecond?: string
       *     timeType?: number
       *     isHideDefault?: boolean
       *     defaultClassId?: string
       *   }>
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      put_api_v1_profiles_timelayouts<
        Config extends Alova2MethodConfig<unknown> & {
          data: TimeLayout;
        }
      >(
        config: Config
      ): Alova2Method<unknown, 'timelayouts.put_api_v1_profiles_timelayouts', Config>;
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api/v1/profiles/timeLayouts/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // [required]
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      get_api_v1_profiles_timelayouts_id<
        Config extends Alova2MethodConfig<unknown> & {
          pathParams: {
            /**
             * [required]
             */
            id: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<unknown, 'timelayouts.get_api_v1_profiles_timelayouts_id', Config>;
      /**
       * ---
       *
       * [PUT]
       *
       * **path:** /api/v1/profiles/timeLayouts/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // [required]
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   isActive?: boolean
       *   attachedObjects?: Record<string, unknown>
       *   name?: string
       *   layouts?: Array<{
       *     isActive?: boolean
       *     attachedObjects?: Record<string, unknown>
       *     startSecond?: string
       *     endSecond?: string
       *     timeType?: number
       *     isHideDefault?: boolean
       *     defaultClassId?: string
       *   }>
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      put_api_v1_profiles_timelayouts_id<
        Config extends Alova2MethodConfig<unknown> & {
          pathParams: {
            /**
             * [required]
             */
            id: string;
          };
          data: TimeLayout;
        }
      >(
        config: Config
      ): Alova2Method<unknown, 'timelayouts.put_api_v1_profiles_timelayouts_id', Config>;
      /**
       * ---
       *
       * [DELETE]
       *
       * **path:** /api/v1/profiles/timeLayouts/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // [required]
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      delete_api_v1_profiles_timelayouts_id<
        Config extends Alova2MethodConfig<unknown> & {
          pathParams: {
            /**
             * [required]
             */
            id: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<unknown, 'timelayouts.delete_api_v1_profiles_timelayouts_id', Config>;
    };
    usersinfo: {
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api/v1/users/info/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // [required]
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      get_api_v1_users_info_id<
        Config extends Alova2MethodConfig<unknown> & {
          pathParams: {
            /**
             * [required]
             */
            id: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<unknown, 'usersinfo.get_api_v1_users_info_id', Config>;
    };
  }

  var Apis: Apis;
}
